sudo: required
services: 
    - docker

before_install:
    - docker build -t shubhammodi004/docker-react Dockerfile.dev .

script: 
    - docker run shubhammodi004/docker-react npm run test -- --coverage

