sudo: required
services: 
    - docker

before_install:
    - docker build -t shubhammodi004/docker-react .

script: 
    - docker run -e CI=true shubhammodi004/docker-react npm run test

deploy: 
    edge: true
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-375410242751"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

